// Generated by scripts/az-read-catalogue.mjs. Do not edit manually.
export const AZ_READ_CATALOGUE = {
  "schemaVersion": 1,
  "status": "catalogue-only; no passthrough execution",
  "generatedFrom": {
    "azureCliVersion": "2.90.0",
    "azureCliCommit": "dc50d475a00ded4a1a1980d4a10a9fbd9a750a81",
    "sdkPackage": "azure-mgmt-resource",
    "sdkVersion": "24.0.0"
  },
  "defaultEffect": "write",
  "defaultAction": "refuse",
  "entries": [
    {
      "command": "group show",
      "effect": "read",
      "handlerClass": "sdk",
      "handler": "azure.mgmt.resource.resources.operations#ResourceGroupsOperations.get",
      "runtime": {
        "package": "azure-cli",
        "version": "2.90.0",
        "distribution": "official trusted Azure CLI",
        "profile": "latest",
        "cloud": "AzureCloud",
        "platforms": [
          "linux",
          "macos",
          "windows"
        ],
        "extensions": [],
        "sdkPackage": "azure-mgmt-resource",
        "sdkVersion": "24.0.0"
      },
      "operations": [
        {
          "method": "GET",
          "path": "/subscriptions/{subscriptionId}/resourcegroups/{resourceGroupName}",
          "apiVersion": "2024-11-01"
        }
      ],
      "credentials": {
        "authentication": "matching az-auth profile, tenant and subscription; ARM token required",
        "permission": "Microsoft.Resources/subscriptions/resourceGroups/read",
        "returns": "none",
        "keyFallback": false
      },
      "arguments": [
        {
          "flags": [
            "--name",
            "-n",
            "--resource-group",
            "-g"
          ],
          "required": true,
          "type": "string",
          "occurrences": 1,
          "minLength": 1,
          "maxLength": 90,
          "pattern": "^[A-Za-z0-9_.()-]+$",
          "constraint": "one literal resource-group name; conservative ASCII subset of SDK name validation"
        },
        {
          "flags": [
            "--subscription"
          ],
          "required": true,
          "type": "uuid",
          "occurrences": 1,
          "constraint": "one explicit effective subscription ID; no names, lists or fan-out"
        }
      ],
      "argumentPolicy": {
        "unknown": "refuse",
        "positionals": "refuse",
        "duplicateAliases": "refuse",
        "globals": "refuse caller-supplied globals, including --ids, --query, --output, --debug and local destinations",
        "transport": "consumer must force JSON, disable prompts and dynamic extension installation"
      },
      "output": {
        "transport": "json",
        "schema": "ResourceGroup",
        "credentialValues": false
      },
      "provenance": [
        {
          "kind": "registration",
          "source": "https://github.com/Azure/azure-cli/blob/dc50d475a00ded4a1a1980d4a10a9fbd9a750a81/src/azure-cli/azure/cli/command_modules/resource/commands.py",
          "commit": "dc50d475a00ded4a1a1980d4a10a9fbd9a750a81",
          "lines": [
            [
              129,
              133
            ],
            [
              313,
              321
            ]
          ],
          "excerptSha256": "cbfb199d1dcedac5acf63cd89d562546b723f141fa38167da2cb38e3ff30839e"
        },
        {
          "kind": "arguments",
          "source": "https://github.com/Azure/azure-cli/blob/dc50d475a00ded4a1a1980d4a10a9fbd9a750a81/src/azure-cli/azure/cli/command_modules/resource/_params.py",
          "commit": "dc50d475a00ded4a1a1980d4a10a9fbd9a750a81",
          "lines": [
            [
              226,
              229
            ]
          ],
          "excerptSha256": "41f5978309fa262c08698346014869957be549924b3c6682f17c3cd960c30d03"
        },
        {
          "kind": "profile",
          "source": "https://github.com/Azure/azure-cli/blob/dc50d475a00ded4a1a1980d4a10a9fbd9a750a81/src/azure-cli-core/azure/cli/core/profiles/_shared.py",
          "commit": "dc50d475a00ded4a1a1980d4a10a9fbd9a750a81",
          "lines": [
            [
              178,
              178
            ]
          ],
          "excerptSha256": "b91cf48c8079ca0d77849e7cdb5fedcd7a12f157ce688344c5c5c3eacc60bd74"
        },
        {
          "kind": "dependency",
          "source": "https://github.com/Azure/azure-cli/blob/dc50d475a00ded4a1a1980d4a10a9fbd9a750a81/src/azure-cli/setup.py",
          "commit": "dc50d475a00ded4a1a1980d4a10a9fbd9a750a81",
          "lines": [
            [
              114,
              114
            ]
          ],
          "excerptSha256": "eb7eaee2957bb61f90d0809b98cf6af5c97fecda559a06faf5a3db58821caebe"
        },
        {
          "kind": "factory",
          "source": "https://github.com/Azure/azure-cli/blob/dc50d475a00ded4a1a1980d4a10a9fbd9a750a81/src/azure-cli/azure/cli/command_modules/resource/_client_factory.py",
          "commit": "dc50d475a00ded4a1a1980d4a10a9fbd9a750a81",
          "lines": [
            [
              7,
              10
            ],
            [
              89,
              90
            ]
          ],
          "excerptSha256": "3f4683bf09831d4ef18e9397595c79837762da758e890db99fde59cea152decb"
        },
        {
          "kind": "operation",
          "source": "https://github.com/Azure/azure-sdk-for-python/blob/c21406d6ab40bfbf81e16ed3699c2dfb73002422/sdk/resources/azure-mgmt-resource/azure/mgmt/resource/resources/v2024_11_01/operations/_operations.py",
          "commit": "c21406d6ab40bfbf81e16ed3699c2dfb73002422",
          "lines": [
            [
              914,
              938
            ],
            [
              6046,
              6096
            ]
          ],
          "excerptSha256": "fcaea978a7e3257cf30fc9a842bdacc4e06e7b8bd9280003235db774905acc7f"
        }
      ]
    }
  ]
} as const;
