// Generated by scripts/az-read-catalogue.mjs. Do not edit manually.
export const AZ_READ_CATALOGUE = {
  "schemaVersion": 1,
  "status": "catalogue-only; no passthrough execution",
  "defaultEffect": "write",
  "defaultAction": "refuse",
  "entries": [
    {
      "command": "group show",
      "effect": "read",
      "handlerClass": "sdk",
      "handler": "azure.mgmt.resource.resources.operations#ResourceGroupsOperations.get",
      "runtime": {
        "package": "azure-cli",
        "version": "2.77.0",
        "distribution": "official trusted Azure CLI",
        "profile": "latest",
        "cloud": "AzureCloud",
        "platforms": [
          "linux",
          "macos",
          "windows"
        ],
        "extensions": [],
        "sdkPackage": "azure-mgmt-resource",
        "sdkVersion": "23.3.0"
      },
      "operations": [
        {
          "method": "GET",
          "path": "/subscriptions/{subscriptionId}/resourcegroups/{resourceGroupName}",
          "apiVersion": "2024-11-01"
        }
      ],
      "credentials": {
        "authentication": "matching az-auth profile, tenant and subscription; ARM token required",
        "permission": "Microsoft.Resources/subscriptions/resourceGroups/read",
        "returns": "none",
        "keyFallback": false
      },
      "arguments": [
        {
          "flags": [
            "--name",
            "-n",
            "--resource-group",
            "-g"
          ],
          "required": true,
          "type": "string",
          "occurrences": 1,
          "minLength": 1,
          "maxLength": 90,
          "pattern": "^[A-Za-z0-9_.()-]+$",
          "constraint": "one literal resource-group name; conservative ASCII subset of SDK name validation"
        },
        {
          "flags": [
            "--subscription"
          ],
          "required": true,
          "type": "uuid",
          "occurrences": 1,
          "constraint": "one explicit effective subscription ID; no names, lists or fan-out"
        }
      ],
      "argumentPolicy": {
        "unknown": "refuse",
        "positionals": "refuse",
        "duplicateAliases": "refuse",
        "globals": "refuse caller-supplied globals, including --ids, --query, --output, --debug and local destinations",
        "transport": "consumer must force JSON, disable prompts and dynamic extension installation"
      },
      "output": {
        "transport": "json",
        "schema": "ResourceGroup",
        "credentialValues": false
      },
      "provenance": [
        {
          "kind": "registration",
          "source": "https://github.com/Azure/azure-cli/blob/387b2e460083431c2afdb45c976cb1b2c8a2aa83/src/azure-cli/azure/cli/command_modules/resource/commands.py",
          "commit": "387b2e460083431c2afdb45c976cb1b2c8a2aa83",
          "lines": [
            [
              129,
              133
            ],
            [
              289,
              297
            ]
          ],
          "excerptSha256": "815c47a0ba115bd898d1603a4c9247b443405e94ebe29ca6617be89c12c668a4"
        },
        {
          "kind": "arguments",
          "source": "https://github.com/Azure/azure-cli/blob/387b2e460083431c2afdb45c976cb1b2c8a2aa83/src/azure-cli/azure/cli/command_modules/resource/_params.py",
          "commit": "387b2e460083431c2afdb45c976cb1b2c8a2aa83",
          "lines": [
            [
              213,
              216
            ]
          ],
          "excerptSha256": "de27a08af09b005a453a1322810c81ab8b41b68a3aafdc13410d2f4ff0a6da3b"
        },
        {
          "kind": "profile",
          "source": "https://github.com/Azure/azure-cli/blob/387b2e460083431c2afdb45c976cb1b2c8a2aa83/src/azure-cli-core/azure/cli/core/profiles/_shared.py",
          "commit": "387b2e460083431c2afdb45c976cb1b2c8a2aa83",
          "lines": [
            [
              178,
              178
            ]
          ],
          "excerptSha256": "d7c3b14643a7f9eca0f165ad8e8ba3c27c3e99d17a19d4454b62d1d92188461d"
        },
        {
          "kind": "dependency",
          "source": "https://github.com/Azure/azure-cli/blob/387b2e460083431c2afdb45c976cb1b2c8a2aa83/src/azure-cli/setup.py",
          "commit": "387b2e460083431c2afdb45c976cb1b2c8a2aa83",
          "lines": [
            [
              111,
              111
            ]
          ],
          "excerptSha256": "4494cd87162dc2fa006453d800f24aeff11b93def24aa0779bfb5f3903eee7f5"
        },
        {
          "kind": "factory",
          "source": "https://github.com/Azure/azure-cli/blob/387b2e460083431c2afdb45c976cb1b2c8a2aa83/src/azure-cli/azure/cli/command_modules/resource/_client_factory.py",
          "commit": "387b2e460083431c2afdb45c976cb1b2c8a2aa83",
          "lines": [
            [
              7,
              10
            ],
            [
              86,
              87
            ]
          ],
          "excerptSha256": "3f4683bf09831d4ef18e9397595c79837762da758e890db99fde59cea152decb"
        },
        {
          "kind": "operation",
          "source": "https://github.com/Azure/azure-sdk-for-python/blob/ef25316618ec0b3b55e49ea51e983809c82e1201/sdk/resources/azure-mgmt-resource/azure/mgmt/resource/resources/v2024_11_01/operations/_operations.py",
          "commit": "ef25316618ec0b3b55e49ea51e983809c82e1201",
          "lines": [
            [
              2356,
              2380
            ],
            [
              10771,
              10820
            ]
          ],
          "excerptSha256": "fcaea978a7e3257cf30fc9a842bdacc4e06e7b8bd9280003235db774905acc7f"
        }
      ]
    }
  ]
} as const;
