export const DESCRIPTION =
  "Read-only Azure inspection for agents: resource inventory, RBAC, activity log, Defender for Cloud and Log Analytics";

export const TOP_LEVEL_HELP = [
  "az-axi                                   # dashboard: profile, identity, subscriptions, alerts, score, exposure, writes",
  "az-axi doctor                            # check az, tokens, ARM reachability and write status per profile",
  "az-axi config init|list|path             # manage profiles in ~/.az-axi/config.json",
  "az-axi sub list                          # subscriptions visible to the identity",
  "az-axi rg query \"<kql>\"                  # Resource Graph query across subscriptions",
  "az-axi rbac list [--privileged]           # role assignments with principal names",
  "az-axi activity list [--since 24h]        # activity log across subscriptions, newest first",
  "az-axi defender alerts|assessments|score  # Defender for Cloud posture",
  "az-axi exposure [--check all]             # internet-exposed resources",
  "az-axi logs query \"<kql>\" --workspace <alias|guid>  # Log Analytics KQL query",
  "az-axi api GET /subscriptions            # escape hatch for any read or query request",
  "",
  "Selector flags on every command: --profile, --tenant, --subscription a,b, --management-group, --config.",
  "Output: TOON on stdout. --full disables truncation, --fields a,b limits list columns, --limit N caps rows.",
  "Read-only by default; $AZ_AXI_READ_ONLY=1 forces read-only for the whole process.",
].join("\n");

export const COMMAND_HELP: Record<string, string> = Object.assign(Object.create(null), {
  home: [
    "az-axi                                   # dashboard: profile, identity, subscriptions, alerts, score, exposure, writes",
    "az-axi home                              # same as above",
    "",
    "Selector flags are accepted. No positional arguments. --help prints this reference.",
    "defender is active alerts by severity. score is the average ascScore and the lowest subscription.",
    "exposure is a count per canned check. A failed section degrades to a hint; the rest still render.",
    "Examples: az-axi; az-axi home; az-axi home --help",
  ].join("\n"),
  doctor: [
    "az-axi doctor [--profile <name>] [--config <path>]",
    "",
    "One row per profile: name, auth, identity, type, subscriptions, writes, status.",
    "Checks: az installed, signed in, arm/logs/graph tokens (graph is optional), ARM reachability, TLS.",
    "help[] lists every failure with the fix, prefixed by the profile name.",
    "Examples: az-axi doctor; az-axi doctor --profile work",
  ].join("\n"),
  config: [
    "az-axi config init [--name <n>] [--auth az|token] [--tenant <t>] [--management-group <mg>]",
    "                   [--subscription a,b] [--workspace alias=<guid>,...] [--token-env arm=VAR,logs=VAR,graph=VAR] [--default]",
    "az-axi config list                       # profiles with scope, write status and description",
    "az-axi config path                       # the config file in use",
    "",
    "Config file order: --config, $AZ_AXI_CONFIG, ./az-axi.config.json, ~/.az-axi/config.json.",
    "Profile selection: --profile, $AZ_AXI_PROFILE, defaultProfile, the only profile, else an implicit az profile.",
    "Examples: az-axi config init --name work --auth az --tenant <tenant-id>; az-axi config list",
  ].join("\n"),
  sub: [
    "az-axi sub list [--limit 50] [--fields name,id,state,inScope] [--full]",
    "",
    "Subscriptions visible to the identity, with inScope marking the active profile's scope.",
    "Examples: az-axi sub list; az-axi sub list --subscription <id>",
  ].join("\n"),
  rg: [
    'az-axi rg query "<kql>" [--subscription a,b] [--management-group mg] [--limit 50] [--skip-token <t>]',
    "az-axi rg query --file query.kql          # multi-line KQL from a file",
    "cat query.kql | az-axi rg query            # multi-line KQL from stdin",
    "",
    "POST /providers/Microsoft.ResourceGraph/resources (api-version 2024-04-01). The query is sent unchanged.",
    "Scope: --subscription/--management-group flags, then profile managementGroup, then profile subscriptions.",
    "Output: total, count, rows; nested objects are compact JSON truncated at 200 chars unless --full.",
    "When a skip token is returned, help[] has the exact command for the next page.",
    'Examples: az-axi rg query "Resources | take 5"; az-axi rg query "Resources | summarize count() by type"',
  ].join("\n"),
  rbac: [
    "az-axi rbac list [--principal <upn|objectId>] [--role <name>] [--scope <armId>] [--privileged] [--limit 50]",
    "az-axi rbac list --show-query              # print the Resource Graph KQL without running it",
    "",
    "One Resource Graph query over authorizationresources, joined to role definitions (api-version 2024-04-01).",
    "Includes assignments inherited from parent management groups and the tenant root.",
    "--privileged keeps Owner, Contributor, User Access Administrator and RBAC Administrator (by GUID).",
    "--principal, --role, --scope and --privileged are applied in the query, then checked on the rows.",
    "Principal names come from Graph getByIds; if names cannot be resolved, raw object IDs are shown with a hint.",
    "Output: total, count, byRole, rows (principal, type, role, scope, created).",
    "Examples: az-axi rbac list --privileged; az-axi rbac list --principal <upn>",
  ].join("\n"),
  activity: [
    "az-axi activity list [--subscription <id>] [--since 24h] [--caller <upn|appId>]",
    "                     [--resource-group <rg>] [--status Failed] [--operation <text>] [--limit 50]",
    "",
    "Activity log per subscription (api-version 2015-04-01), merged newest first; --since older than 90d is rejected.",
    "Scope: --subscription, else --management-group or the profile scope. Management groups expand to subscriptions.",
    "Server filter: time range plus resourceGroupName. caller is not a legal $filter field, so caller, status and operation filter client-side while paging.",
    "Output: total, count, topCallers, rows (time, caller, operation, status, resource).",
    "Examples: az-axi activity list --since 24h --status Failed",
  ].join("\n"),
  defender: [
    "az-axi defender alerts [--severity High,Medium] [--status Active] [--since 7d] [--limit 50]",
    "az-axi defender alerts get <alert-resource-id>",
    "az-axi defender assessments [--severity High] [--status Unhealthy] [--limit 25]",
    "az-axi defender assessments --resource <name>   # per-resource rows; name matches a path segment, not the recommendation",
    "az-axi defender score",
    "",
    "Alerts come from ARM per subscription (api-version 2022-01-01), newest first.",
    "Default --status is Active. --status all lists every status. Omitting --since lists every retained alert.",
    "Flags that do not apply to the subcommand are rejected. `get` takes the full alert resource ID only.",
    "Assessments and score come from Resource Graph securityresources (api-version 2024-04-01).",
    "Assessments: one row per recommendation (recommendation, severity, unhealthyCount, total), worst severity first.",
    "Score is the ascScore for each subscription (current, max, percent), lowest percent first.",
    "--show-query on assessments prints the exact KQL without running it.",
    "Examples: az-axi defender alerts --severity High; az-axi defender assessments --severity High; az-axi defender score",
  ].join("\n"),
  exposure: [
    "az-axi exposure [--check public-ips|mgmt-ports|any-any|all] [--limit 50]",
    "az-axi exposure --show-query              # print the canned Resource Graph KQL without running it",
    "",
    "Canned Resource Graph queries (api-version 2024-04-01). public-ips is attached addresses only.",
    "mgmt-ports matches ports 22, 3389, 5985 and 5986 exactly, including ranges. any-any is any source to any port.",
    "Default --check all returns per-check counts plus the first 10 rows of each. --limit changes that cap.",
    "A failed check degrades to a hint; the others still render.",
    "Output: total, count, checks{<check>: count plus rows (resource, resourceGroup, subscription, detail)}.",
    "Examples: az-axi exposure; az-axi exposure --check mgmt-ports",
  ].join("\n"),
  logs: [
    "az-axi logs query \"<kql>\" --workspace <alias|guid> [--timespan P1D] [--limit 50]",
    "az-axi logs query --file hunt.kql --workspace sentinel",
    "cat hunt.kql | az-axi logs query --workspace sentinel   # multi-line KQL from stdin",
    "",
    "POST /v1/workspaces/{id}/query on api.loganalytics.io. Surrounding query whitespace is trimmed; no row limits or time filters are added to the KQL.",
    "--workspace takes an alias from the profile or the workspace ID GUID; ARM resource IDs are rejected with the rg query that finds the GUID.",
    "--timespan defaults to P1D and intersects any time filter in the query. It accepts 30m, 24h, 7d, an ISO 8601 duration, an ISO date (from that instant until now), or a start/end interval.",
    "Output: total, count, rows from the first table; otherTables lists only names and row counts for extra tables.",
    "--limit caps displayed rows client-side (default 50), including with --full; capped results hint at '| take' or '| summarize'.",
    "Strings and compact JSON cells truncate at 200 chars unless --full. Datetimes and resource IDs are not shortened.",
    "Partial errors (HTTP 200 with an error object) return a warning instead of failing.",
    "Examples: az-axi logs query \"SigninLogs | take 5\" --workspace sentinel",
  ].join("\n"),
  api: [
    "az-axi api [GET|POST|PUT|PATCH|DELETE] <path> [--resource arm|logs|graph] [--api-version <v>]",
    "         [--query 'k=v&k2=v2'] [--body '<json>'] [--raw] [--all]",
    "az-axi api /subscriptions --api-version 2022-12-01",
    "",
    "Escape hatch for any read or query request. Paths are relative to the host root.",
    "--api-version is required for arm when the path has no api-version query parameter.",
    "Lists with a value[] array return count plus value; --all follows ARM nextLink (up to 10 pages).",
    "Strings truncate at 4,000 chars unless --full. Writes are blocked with WRITES_DISABLED; only reads and queries are served.",
    "Examples: az-axi api /subscriptions --api-version 2022-12-01",
  ].join("\n"),
});
